import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";

// Migration SQL is generated by `pnpm db:generate` (drizzle-kit) from
// src/schema.ts. RLS policies are appended post-generation since Drizzle
// does not model RLS natively. These tests verify the full migration contract
// including the appended security invariants.

const migrationPath = new URL(
  "../drizzle/0000_yielding_inertia.sql",
  import.meta.url,
);

describe("drizzle migration: 0000_yielding_inertia", () => {
  it("creates all five tenant-scoped tables", async () => {
    const sql = await readFile(migrationPath, "utf8");
    const tables = [
      "approval_feedback",
      "event_outbox",
      "motion_scores",
      "motion_stack",
      "workflow_runs",
    ];
    for (const table of tables) {
      expect(sql).toContain(`CREATE TABLE "growthos"."${table}"`);
    }
  });

  it("enforces event_outbox idempotency via unique constraint", async () => {
    const sql = await readFile(migrationPath, "utf8");
    expect(sql).toContain('"idempotency_key" text NOT NULL');
    expect(sql).toContain(
      'CONSTRAINT "event_outbox_idempotency_unique" UNIQUE("tenant_id","event_type","idempotency_key")',
    );
  });

  it("enforces workflow_runs state machine via CHECK constraint", async () => {
    const sql = await readFile(migrationPath, "utf8");
    expect(sql).toContain("\"state\" text DEFAULT 'requested' NOT NULL");
    expect(sql).toContain('CONSTRAINT "workflow_runs_state_check" CHECK');
    expect(sql).toContain("'requested', 'in_progress', 'completed', 'failed'");
  });

  it("enables and forces RLS on all tenant-scoped tables", async () => {
    const sql = await readFile(migrationPath, "utf8");
    for (const table of [
      "approval_feedback",
      "event_outbox",
      "motion_scores",
      "motion_stack",
      "workflow_runs",
    ]) {
      expect(sql).toContain(
        `ALTER TABLE "growthos"."${table}" ENABLE ROW LEVEL SECURITY`,
      );
      expect(sql).toContain(
        `ALTER TABLE "growthos"."${table}" FORCE ROW LEVEL SECURITY`,
      );
      expect(sql).toContain(`${table}_tenant_isolation`);
    }
  });

  it("workflow_runs has unique constraint on (tenant_id, workflow_id)", async () => {
    const sql = await readFile(migrationPath, "utf8");
    expect(sql).toContain(
      'CONSTRAINT "workflow_runs_tenant_workflow_unique" UNIQUE("tenant_id","workflow_id")',
    );
  });

  it("all tables have tenant_id column", async () => {
    const sql = await readFile(migrationPath, "utf8");
    // Each CREATE TABLE block should contain a tenant_id uuid NOT NULL column
    const blocks = sql
      .split("CREATE TABLE")
      .slice(1)
      .filter((b) => !b.startsWith("\n--"));
    for (const block of blocks) {
      expect(block).toContain('"tenant_id" uuid NOT NULL');
    }
  });
});
