apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: api-deployment-pull.yaml
  - path: web-deployment-pull.yaml

labels:
  - pairs:
      growthos.dev/registry-auth: ghcr
    includeSelectors: false
